services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    command: npm run dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017/product-catalog}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_TTL: ${REDIS_TTL:-3600}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}

  mongodb:
    image: mongo:7.0.8
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}

volumes:
  mongodb_data:
  redis_data:
